[project]
name = "foundation-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.11.1",
    "grain>=0.2.11",
    "jax>=0.7.0",
    "matplotlib>=3.10.5",
    "optax>=0.2.5",
]
